# Generated by Django 5.1 on 2026-09-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(default='steadfast', max_length=50, unique=True)),
                ('display_name', models.CharField(default='Steadfast Courier', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('secret_key', models.CharField(blank=True, max_length=255, verbose_name='Secret Key')),
                ('base_url', models.URLField(default='https://portal.steadfast.com.bd/api/v1', verbose_name='Base URL')),
                ('auto_send_on_confirm', models.BooleanField(default=True, help_text='Automatically book parcel on Steadfast when order is confirmed')),
                ('test_mode', models.BooleanField(default=False, help_text='Simulate responses without real API calls')),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier Configuration',
                'verbose_name_plural': 'Courier Configurations',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Linked customer contact from Messaging Hub', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='messaging.contact'),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_channel',
            field=models.CharField(choices=[('POS', 'In-Store POS'), ('ONLINE', 'Online Order'), ('WHATSAPP', 'WhatsApp Order'), ('MESSENGER', 'Facebook Messenger'), ('TELEGRAM', 'Telegram Order'), ('PHONE', 'Phone Call'), ('OTHER', 'Other Channel')], db_index=True, default='POS', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Delivery Street Address'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Delivery Notes / Instructions'),
        ),
        migrations.AddField(
            model_name='sale',
            name='courier_service',
            field=models.CharField(default='steadfast', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='courier_consignment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='courier_tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='courier_status',
            field=models.CharField(choices=[('none', 'Not Dispatched'), ('pending', 'Pending Pickup'), ('in_review', 'In Review (Steadfast)'), ('in_transit', 'In Transit / On the Way'), ('delivered', 'Delivered Successfully'), ('partial_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled / Returned')], db_index=True, default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='courier_booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='courier_response_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
