# Generated by Django 5.1.15 on 2026-09-22 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company')),
                ('avatar_color', models.CharField(default='#7C3AED', max_length=7)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (comma-separated)')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('messenger_id', models.CharField(blank=True, max_length=100)),
                ('instagram_id', models.CharField(blank=True, max_length=100)),
                ('telegram_id', models.CharField(blank=True, max_length=100)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Facebook Messenger'), ('instagram', 'Instagram DM'), ('telegram', 'Telegram'), ('email', 'Email'), ('internal', 'Internal Note')], default='whatsapp', max_length=30)),
                ('platform_thread_id', models.CharField(blank=True, help_text='External thread/chat ID on the platform', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('pending', 'Pending'), ('spam', 'Spam')], default='open', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='messaging.contact')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (Received)'), ('outbound', 'Outbound (Sent)')], default='inbound', max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('template', 'Template'), ('note', 'Internal Note')], default='text', max_length=15)),
                ('body', models.TextField(blank=True, verbose_name='Message Body')),
                ('media_url', models.URLField(blank=True, verbose_name='Media URL')),
                ('media_mime', models.CharField(blank=True, max_length=100)),
                ('platform_message_id', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Facebook Messenger'), ('instagram', 'Instagram DM'), ('telegram', 'Telegram'), ('email', 'Email'), ('internal', 'Internal Note')], help_text='Leave blank to apply to all platforms', max_length=30)),
                ('category', models.CharField(blank=True, help_text='e.g. greeting, follow-up, promotion', max_length=50)),
                ('body', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names like ["name", "order_id"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Facebook Messenger'), ('instagram', 'Instagram DM'), ('telegram', 'Telegram'), ('email', 'Email'), ('internal', 'Internal Note')], max_length=30, unique=True, verbose_name='Platform')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('access_token', models.TextField(blank=True, verbose_name='Access Token / API Key')),
                ('phone_number_id', models.CharField(blank=True, max_length=100, verbose_name='Phone Number ID')),
                ('business_account_id', models.CharField(blank=True, max_length=100, verbose_name='Business Account ID')),
                ('app_id', models.CharField(blank=True, max_length=100, verbose_name='App ID')),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255, verbose_name='Webhook Verify Token')),
                ('bot_token', models.CharField(blank=True, max_length=255, verbose_name='Bot Token')),
                ('bot_username', models.CharField(blank=True, max_length=100, verbose_name='Bot Username')),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.EmailField(blank=True, max_length=254)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configurations',
            },
        ),
    ]
