# Generated by Django 5.1.15 on 2026-09-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Daizzy.online', max_length=200)),
                ('store_address', models.TextField(blank=True, default='Dhaka, Bangladesh')),
                ('phone', models.CharField(blank=True, default='+880 1700-000000', max_length=30)),
                ('email', models.EmailField(blank=True, default='contact@daizzy.online', max_length=254)),
                ('website', models.URLField(blank=True, default='https://daizzy.online')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('currency_symbol', models.CharField(default='৳', max_length=5)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('invoice_number_format', models.CharField(default='{prefix}-{year}-{seq:06d}', help_text='Template for invoice code generation', max_length=100)),
                ('barcode_format', models.CharField(choices=[('INTERNAL', 'Internal Sequential (DZY-000000001)'), ('CODE128', 'Code 128 Standard'), ('EAN13', 'EAN-13 (GS1 compatible)')], default='INTERNAL', max_length=30)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('default_discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('low_stock_threshold', models.PositiveSmallIntegerField(default=5)),
                ('receipt_width_mm', models.PositiveSmallIntegerField(choices=[(58, '58 mm Thermal'), (80, '80 mm Thermal')], default=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
