# Generated by Django 5.1.15 on 2026-09-17 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE', 'Stock Addition (Purchase)'), ('SALE', 'POS Sale Deduction'), ('RETURN', 'Sales Return Inward'), ('ADJUSTMENT_IN', 'Manual Adjustment (Increase)'), ('ADJUSTMENT_OUT', 'Manual Adjustment (Decrease)'), ('DAMAGE', 'Damaged Inventory'), ('LOSS', 'Lost / Stolen Stock'), ('CORRECTION', 'Inventory Count Correction')], db_index=True, max_length=30)),
                ('quantity', models.PositiveIntegerField(help_text='Volume of items moved (always positive)')),
                ('direction', models.SmallIntegerField(choices=[(1, 'IN (+)'), (-1, 'OUT (-)')], help_text='+1 for stock addition, -1 for deduction')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, help_text='e.g. sale, return, adjustment', max_length=50)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_index=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
